// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Dokument
{

    public Dokument(int id, DateTime datNast, string stavka, string format, int idVrsteDokumenta, int idProjekta)
    {
        IdDokumenta = id;
        DatumNastanka = datNast;
        Stavka = stavka;
        Format = format;
        IdVrsteDokumenta = idVrsteDokumenta;
        IdProjekta = idProjekta;
    }

    public Dokument(DateTime datNast, string stavka, string format, int idVrsteDokumenta, int idProjekta)
    {
        DatumNastanka = datNast;
        Stavka = stavka;
        Format = format;
        IdVrsteDokumenta = idVrsteDokumenta;
        IdProjekta = idProjekta;
    }

    public Dokument(){}

    public int IdDokumenta { get; set; }

    public DateTime DatumNastanka { get; set; }

    public string Stavka { get; set; }

    public string Format { get; set; }

    public int IdVrsteDokumenta { get; set; }

    public int IdProjekta { get; set; }

    public virtual Projekt IdProjektaNavigation { get; set; }

    public virtual VrstaDokumenta IdVrsteDokumentaNavigation { get; set; }
}
