// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class EvidencijaUloga
{
    public int IdEvidencijaUloga { get; set; }

    public DateTime DatumPocetka { get; set; }

    public DateTime DatumZavrsetka { get; set; }

    public int IdProjekta { get; set; }

    public int IdUloge { get; set; }

    public int Oibosoba { get; set; }

    public virtual Projekt IdProjektaNavigation { get; set; }

    public virtual Uloga IdUlogeNavigation { get; set; }

    public virtual Osoba OibosobaNavigation { get; set; }
}