// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class EvidencijaRada
{
    //public IEnumerable<EvidencijaRada> radic { get; set; }

    public EvidencijaRada(int id, string opis, DateTime datumRada, int vrijemeRada, int oibOsoba, int idZadatka, int idVrstePosla)
    {
        IdEvidencijaRad = id;
        Opis = opis;
        DatumRada = datumRada;
        VrijemeRada = vrijemeRada;
        Oibosoba = oibOsoba;
        IdZadatka = idZadatka;
        IdVrstePosla = idVrstePosla;
    }
    
    public EvidencijaRada(string opis, DateTime datumRada, int vrijemeRada, int oibOsoba, int idZadatka, int idVrstePosla)
    {
        Opis = opis;
        DatumRada = datumRada;
        VrijemeRada = vrijemeRada;
        Oibosoba = oibOsoba;
        IdZadatka = idZadatka;
        IdVrstePosla = idVrstePosla;
    }
    
    public EvidencijaRada()
    {
        
    }
    
    public int IdEvidencijaRad { get; set; }

    public string Opis { get; set; }
    public DateTime DatumRada { get; set; }
    public int VrijemeRada { get; set; }
    
    public int Oibosoba { get; set; }

    public int IdZadatka { get; set; }

    public int IdVrstePosla { get; set; }

    public virtual VrstaPosla IdVrstePoslaNavigation { get; set; }

    public virtual Zadatak IdZadatkaNavigation { get; set; }

    public virtual Osoba OibosobaNavigation { get; set; }
}