// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Narucitelj
{
    public int Oibnarucitelj { get; set; }

    public string Naziv { get; set; }

    public int Kontakt { get; set; }

    public int Iban { get; set; }

    public virtual ICollection<Projekt> Projekts { get; set; } = new List<Projekt>();
}