// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Organizacija
{
    public int IdOrganizacije { get; set; }

    public string Naziv { get; set; }

    public string Adresa { get; set; }

    public virtual ICollection<Osoba> Osobas { get; set; } = new List<Osoba>();
}