// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Osoba
{
    public int Oibosoba { get; set; }

    public string Ime { get; set; }

    public string Prezime { get; set; }

    public string Mail { get; set; }

    public int BrTelefon { get; set; }

    public int IdOrganizacije { get; set; }

    public virtual ICollection<EvidencijaRada> EvidencijaRada { get; set; } = new List<EvidencijaRada>();

    public virtual ICollection<EvidencijaUloga> EvidencijaUlogas { get; set; } = new List<EvidencijaUloga>();

    public virtual Organizacija IdOrganizacijeNavigation { get; set; }

    public virtual ICollection<ProjektnaKartica> ProjektnaKarticas { get; set; } = new List<ProjektnaKartica>();

    public virtual ICollection<Zadatak> Zadataks { get; set; } = new List<Zadatak>();
}