// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Prioritet
{
    public Prioritet(int id, string naziv)
{
    this.IdPrioriteta = id;
    this.Naziv = naziv; 
}

    public Prioritet(string naziv)
    {
        this.Naziv = naziv;
    }

    public Prioritet()
    {
    }
    public int IdPrioriteta { get; set; }

    public string Naziv { get; set; }

    public virtual ICollection<Zadatak> Zadataks { get; set; } = new List<Zadatak>();

    public virtual ICollection<Zahtjev> Zahtjevs { get; set; } = new List<Zahtjev>();
}