// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Status
{
    public Status(int id, string naziv) {
        this.IdStatus = id; 
        this.Naziv = naziv;
    }

    public Status(string naziv)
    {
        this.Naziv = naziv;
    }

    public Status()
    {
    }
    public int IdStatus { get; set; }

    public string Naziv { get; set; }

    public virtual ICollection<Zadatak> Zadataks { get; set; } = new List<Zadatak>();
}