// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Transakcija
{
    public int IdTransakcije { get; set; }

    public decimal Iznos { get; set; }

    public int Iban2zaTransakciju { get; set; }

    public DateTime Datum { get; set; }

    public TimeSpan Vrijeme { get; set; }

    public int IdVrsteTransakcije { get; set; }

    public int IdKartice { get; set; }

    public virtual ProjektnaKartica IdKarticeNavigation { get; set; }

    public virtual VrstaTransakcije IdVrsteTransakcijeNavigation { get; set; }
}