// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class VrstaZahtjeva
{
    public VrstaZahtjeva(int id, string naziv, string opis)
    {
        this.IdVrsteZahtjeva = id;
        this.Naziv = naziv;
        this.Opis = opis;
    }

    public VrstaZahtjeva(string naziv, string opis)
    {
        this.Naziv = naziv;
        this.Opis = opis;
    }

    public VrstaZahtjeva()
    {
    }
    public int IdVrsteZahtjeva { get; set; }

    public string Naziv { get; set; }

    public string Opis { get; set; }

    public virtual ICollection<Zahtjev> Zahtjevs { get; set; } = new List<Zahtjev>();
}