// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class VrstaPosla
{
    public int IdVrstePosla { get; set; }

    public string Naziv { get; set; }

    public virtual ICollection<EvidencijaRada> EvidencijaRada { get; set; } = new List<EvidencijaRada>();
}