// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class VrstaDokumenta
{
    public int IdVrsteDokumenta { get; set; }

    public string Naziv { get; set; }

    public string Opis { get; set; }

    public virtual ICollection<Dokument> Dokuments { get; set; } = new List<Dokument>();
}