// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

public partial class Zadatak
{
    public Zadatak(int ID, string zadatakImeZadatka, DateTime zadatakPlaniraniPocetak, DateTime zadatakPlaniraniZavrsetak, DateTime zadatakStvarniPocetak, DateTime zadatakStvarniZavrsetak, int idZahtjeva, int idStatusa, int zadatakOibosoba, int idPrioriteta)
    {
        IdZadatka = ID;
        ImeZadatka = zadatakImeZadatka;
        PlaniraniPocetak = zadatakPlaniraniPocetak;
        PlaniraniZavrsetak = zadatakPlaniraniZavrsetak;
        StvarniPocetak = zadatakStvarniPocetak;
        StvarniZavrsetak = zadatakStvarniZavrsetak;
        IdZahtjeva = idZahtjeva;
        IdStatus = idStatusa;
        Oibosoba = zadatakOibosoba;
        IdPrioriteta = idPrioriteta;
    }
    
    
    public Zadatak(string zadatakImeZadatka, DateTime zadatakPlaniraniPocetak, DateTime zadatakPlaniraniZavrsetak, DateTime zadatakStvarniPocetak, DateTime zadatakStvarniZavrsetak, int idZahtjeva, int idStatusa, int zadatakOibosoba, int idPrioriteta)
    {
        ImeZadatka = zadatakImeZadatka;
        PlaniraniPocetak = zadatakPlaniraniPocetak;
        PlaniraniZavrsetak = zadatakPlaniraniZavrsetak;
        StvarniPocetak = zadatakStvarniPocetak;
        StvarniZavrsetak = zadatakStvarniZavrsetak;
        IdZahtjeva = idZahtjeva;
        IdStatus = idStatusa;
        Oibosoba = zadatakOibosoba;
        IdPrioriteta = idPrioriteta;
    }

    public Zadatak()
    {
        EvidencijaRada = new HashSet<EvidencijaRada>();
    }

    public int IdZadatka { get; set; }
    
    public string ImeZadatka { get; set; }
    public DateTime PlaniraniPocetak { get; set; }

    public DateTime PlaniraniZavrsetak { get; set; }

    public DateTime StvarniPocetak { get; set; }

    public DateTime StvarniZavrsetak { get; set; }

    public int IdZahtjeva { get; set; }

    public int IdStatus { get; set; }

    public int Oibosoba { get; set; }

    public int IdPrioriteta { get; set; }

    public virtual ICollection<EvidencijaRada> EvidencijaRada { get; set; } = new List<EvidencijaRada>();

    public virtual Prioritet IdPrioritetaNavigation { get; set; }

    public virtual Status IdStatusNavigation { get; set; }

    public virtual Zahtjev IdZahtjevaNavigation { get; set; }

    public virtual Osoba OibosobaNavigation { get; set; }
}