// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Zahtjev
{
    public Zahtjev() {
        Zadataks = new HashSet<Zadatak>();
    }

    public Zahtjev(int idZahtjeva, string naslov, string opis, int idVrsta, int idPrioritet, int idProjekt)
    {
        this.IdZahtjeva = idZahtjeva;
        this.Naslov = naslov;
        this.Opis = opis;
        this.IdVrsteZahtjeva = idVrsta;
        this.IdPrioriteta = idPrioritet;
        this.IdProjekta = idProjekt;
    }

    public Zahtjev(string naslov, string opis, int idVrsta, int idPrioritet, int idProjekt)
    {
        this.Naslov = naslov;
        this.Opis = opis;
        this.IdVrsteZahtjeva = idVrsta;
        this.IdPrioriteta = idPrioritet;
        this.IdProjekta = idProjekt;
    }

    public int IdZahtjeva { get; set; }

    public string Naslov { get; set; }

    public string Opis { get; set; }

    public int IdVrsteZahtjeva { get; set; }

    public int IdPrioriteta { get; set; }

    public int IdProjekta { get; set; }

    public virtual Prioritet IdPrioritetaNavigation { get; set; }

    public virtual Projekt IdProjektaNavigation { get; set; }

    public virtual VrstaZahtjeva IdVrsteZahtjevaNavigation { get; set; }

    public virtual ICollection<Zadatak> Zadataks { get; set; } = new List<Zadatak>();
}